mkdir -p tmp/SnD_other_dim
rm tmp/SnD_other_dim/*
python SnD.py data/classify/diabetes.csv | tee tmp/SnD_other_dim/diabetes.csv &
python SnD.py data/classify/soybean.csv | tee tmp/SnD_other_dim/soybean.csv &
python SnD.py data/config/Apache_AllMeasurements.csv | tee tmp/SnD_other_dim/Apache_AllMeasurements.csv &
python SnD.py data/config/SQL_AllMeasurements.csv | tee tmp/SnD_other_dim/SQL_AllMeasurements.csv &
python SnD.py data/config/SS-J.csv | tee tmp/SnD_other_dim/SS-J.csv &
python SnD.py data/config/SS-K.csv | tee tmp/SnD_other_dim/SS-K.csv &
python SnD.py data/config/SS-L.csv | tee tmp/SnD_other_dim/SS-L.csv &
python SnD.py data/config/SS-M.csv | tee tmp/SnD_other_dim/SS-M.csv &
python SnD.py data/config/SS-N.csv | tee tmp/SnD_other_dim/SS-N.csv &
python SnD.py data/config/SS-O.csv | tee tmp/SnD_other_dim/SS-O.csv &
python SnD.py data/config/SS-P.csv | tee tmp/SnD_other_dim/SS-P.csv &
python SnD.py data/config/SS-Q.csv | tee tmp/SnD_other_dim/SS-Q.csv &
python SnD.py data/config/SS-R.csv | tee tmp/SnD_other_dim/SS-R.csv &
python SnD.py data/config/SS-S.csv | tee tmp/SnD_other_dim/SS-S.csv &
python SnD.py data/config/SS-T.csv | tee tmp/SnD_other_dim/SS-T.csv &
python SnD.py data/config/SS-U.csv | tee tmp/SnD_other_dim/SS-U.csv &
python SnD.py data/config/SS-V.csv | tee tmp/SnD_other_dim/SS-V.csv &
python SnD.py data/config/SS-W.csv | tee tmp/SnD_other_dim/SS-W.csv &
python SnD.py data/config/SS-X.csv | tee tmp/SnD_other_dim/SS-X.csv &
python SnD.py data/config/X264_AllMeasurements.csv | tee tmp/SnD_other_dim/X264_AllMeasurements.csv &
python SnD.py data/misc/HSMGP_num.csv | tee tmp/SnD_other_dim/HSMGP_num.csv &
python SnD.py data/misc/Wine_quality.csv | tee tmp/SnD_other_dim/Wine_quality.csv &
python SnD.py data/misc/rs-6d-c3_obj1.csv | tee tmp/SnD_other_dim/rs-6d-c3_obj1.csv &
python SnD.py data/misc/rs-6d-c3_obj2.csv | tee tmp/SnD_other_dim/rs-6d-c3_obj2.csv &
python SnD.py data/misc/sol-6d-c2-obj1.csv | tee tmp/SnD_other_dim/sol-6d-c2-obj1.csv &
python SnD.py data/misc/wc-6d-c1-obj1.csv | tee tmp/SnD_other_dim/wc-6d-c1-obj1.csv &
python SnD.py data/old/china.csv | tee tmp/SnD_other_dim/china.csv &
python SnD.py data/process/coc1000.csv | tee tmp/SnD_other_dim/coc1000.csv &
python SnD.py data/process/nasa93dem.csv | tee tmp/SnD_other_dim/nasa93dem.csv &
python SnD.py data/process/pom3a.csv | tee tmp/SnD_other_dim/pom3a.csv &
python SnD.py data/process/pom3b.csv | tee tmp/SnD_other_dim/pom3b.csv &
python SnD.py data/process/pom3c.csv | tee tmp/SnD_other_dim/pom3c.csv &
python SnD.py data/process/pom3d.csv | tee tmp/SnD_other_dim/pom3d.csv &
python SnD.py data/process/xomo_flight.csv | tee tmp/SnD_other_dim/xomo_flight.csv &
python SnD.py data/process/xomo_ground.csv | tee tmp/SnD_other_dim/xomo_ground.csv &
python SnD.py data/process/xomo_osp.csv | tee tmp/SnD_other_dim/xomo_osp.csv &
python SnD.py data/process/xomo_osp2.csv | tee tmp/SnD_other_dim/xomo_osp2.csv &
