#!/usr/bin/env bash
# vim: set filetype=awk ts=2 sw=2 et :

code() { cat <<-'EOF' | sed -e 's/Data/rows,br,Col,Num,Sym/g' \
                            -e 's/Col/name,pos,w,xx,yy/g'      \
                            -e 's/Num/nn,mu,m2,sd,hi,lo/g'      \
                            -e 's/Sym/seen/g'                    \
                            -e '1s/^/\n\n\n\n\n\n\n\n/'
BEGIN { FS=","; BINS=4; srand(SEED); main()}

function main(    Data,a,row) {
  row = -1
   while(getline>0)  {
     row++
     if (row>0) {split($0,rows[row],","); body(Data,rows[row])
     } else     {split($0,a,",");         head(Data,a)}
  }
   stop(Data) }

function head(Data,row,     c,z) { print(1000)
  start(Data)
  for(c in row) {
    z = row[c]
    if(z !~ /X$/) {
      name[c] = z
      pos[c] = z
      if (z~/^[A-Z]/) {num0(Data,c)} else {seen[c]};
      if (z~/-$/)    yy[c]=0;
      if (z~/+$/)    yy[c]=1;
      if (!(c in yy)) xx[c] }}}

function start(Data) {print(10)}
function stop(Data,     k)  { 
  for(k in SYMTAB) if (k ~ /^[a-z]/) print "?? "k }
  
function body(Data,row,    c) {  
  for(c in row) 
    if (row[c] != "?") {
      nn[c]++
      c in mu ? num(Data,c,row[c]+=0) : seen[c][row[c]]++ }}

function learn(Data,row,    c,d) {
  d = chebyshev(Data,row) 
  for(c in xx) { 
    br[c][bin(c,row[c])] += d }}

function chebyshev(Data,row,     c,d) {
  d=0; for(c in yy) d = max(d, abs(norm(Data,c,row[c]) - yy[c]));
  return d }

function bin(Data,c,x) { return int(BINS*cdf(x,lo[c],hi[c],mu[c])) }

function cdf(x,a,b,c) {
  if (a < x && x <= c) return     (x-a)^2/((b-a)*(c-a));
  if (c < x && x <= b) return 1 - (b-x)^2/((b-a)*(b-c));
  return 0 }

function num0(Data,c) { nn[c]=0; lo[c]=1E32; hi[c]=-1E32 }

function num(Data,c,x,     d) {
  if (x > hi[c]) hi[c]=x;
  if (x < lo[c]) lo[c]=x;
  d      = x - mu[c];
  mu[c] += d/nn[c] 
  m2[c] += d*(x-mu[c]);
  sd[c]  = nn[c] < 2 ? 0 : (m2[c]/(nn[c] - 1))^0.5 }

function norm(Data,c,x) { return (x-lo[c])/(hi[c]-lo[c] + 1E-32) }
function max(x,y)  { return x>y? x : y }
function abs(x)    { return x>0? x : -x }
function cat(a, s,k) { s=a[1]; for(k=2;k<=length(a);k++) s=s ", " a[k]; return "("s")" } 

# https://real-statistics.com/other-key-distributions/uniform-distribution/triangular-distribution/
function fdc(Data,c,p) { return fdc1(p, lo[c],hi[c],mu[c]) }
function fdc1(p,a,b,c) {
  return (0 <= p && p < (c-a)/(b-a)) ? a+sqrt((b-a)*(c-a)*p) : b-sqrt((b-a)*(b-c)*(1-p)) }

EOF
}
[[ -t 1 ]] && gawk --source "$(code)" $* || cat - | gawk --source "$(code)" $*
